Repository madeleine-patience/Considerate-Cat-Version-2-With-Next, pull requests merged in 2024-09, with the labels that each got.

#15 Updates to .gitignore
  .gitignore
Labels: enhancement

#10 Deleted unused component
  components/displayTarotCards copy/DisplayTarotCards.tsx
Labels: refactor

#17 Refactor of Purrlaroid Component
  components/purrlaroid/PurrlaroidRoot.tsx
  components/purrlaroid/PurrlaroidTitle.tsx
  components/purrlaroid/index.ts
  components/purrlaroid/purrlaroid.stories.tsx
  pages/CatDirectory.tsx
Labels: refactor

#37 Fixes #32 storybook display issue tarot dialog
  components/tarotDialog/TarotDialog.tsx
  components/tarotDialog/index.tsx
  theme/themeBuilder.ts
Labels: bug, enhancement

#35 Refactored purrlaroid further
  components/purrlaroid/index.ts
  components/purrlaroid/index.tsx
  components/purrlaroid/purrlaroid.stories.tsx
  package-lock.json
  pages/CatDirectory.tsx
Labels: refactor

#39 Fixes #36 contributor and style guide
  .env.example
  .eslintcache
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .prettierrc
  CONTRIBUTING.md
  README.md
  components/tarotDialog/TarotDialog.tsx
  package-lock.json
  package.json
  public/image/cc-homepage.webp
  supabase.js
Labels: documentation, enhancement

#45 19 alt padding issue in tarotspreadcontainer
  README.md
  components/headerButton/HeaderButton.tsx
  components/tarotSpreadSelectionBox/TarotSpreadSelectionBox.tsx
  components/tarotSpreadSelectionBox/getLayout.ts
  components/tarotSpreadSelectionBox/getLayoutStyles.ts
  components/tarotSpreadSelectionBoxList/TarotSpreadSelectionBoxList.tsx
  context/TarotDeckContext.ts
  package.json
  pages/TarotReadPage.tsx
  types/tarotDeckData.ts
Labels: enhancement

#48 Replaced hotlinks with public/image images
  components/loadingPage/LoadingPage.tsx
  pages/index.tsx
  public/image/homepageImage.webp
  public/image/kneadingTheDough.webp
Labels: refactor
